### PR TITLE
feat(wanda): add dns config into pod's template

### PR DESCRIPTION
**Pull request by moshuipan**
**What this PR does / why we need it**:

feat(wanda): add dns config into pod's template

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @whalecold 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by whalecold** [comment]
在 readme 和 value.yaml 也加上用例吧 @moshuipan

**Comment by moshuipan** [comment]
> 在 readme 和 value.yaml 也加上用例吧 @moshuipan

加了

**Comment by moshuipan** [comment]
Reference to #  https://github.com/caicloud/prod-issue/issues/677

**Pull request merged**
