### PR TITLE
[PAPER-63]feat(release): add eureka cluster release in application store

### PR DESCRIPTION
**Pull request by FogDong**
**What this PR does / why we need it**:

feat(release): add eureka cluster release in application store

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to 

**Special notes for your reviewer**:

/cc @whalecold @hezhizhen @quasimodo7614 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hezhizhen** [comment]
cla 没过。
LGTM

**Comment by whalecold** [comment]
合太快了..

**Pull request merged**
