### PR TITLE
[BEST-73]remove default service selector

### PR DESCRIPTION
**Pull request by wzqnls**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #
- [JIRA](http://jira.caicloud.xyz/browse/BEST-73)
- [设计文档](https://docs.google.com/document/d/1ZIu_zh7Zier92rAPWEuwQJmljwA11X_NPiBYAQlTXkY/edit#heading=h.ya7pnmlqeft2)

**Special notes for your reviewer**:

/cc @your-reviewer

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by whalecold** [comment]
把相关 jira 的链接也贴一下吧 @wzqnls

**Comment by qianlei90** [comment]
就直接删了吧，就不用注释掉了..

**Comment by qianlei90** [comment]
这个 PR 影响到了应用商店中新建的东西，默认的 service 都没有 selector 了

**Pull request merged**
