### PR TITLE
fix: remove selectors from templates for cronjobs and jobs

### PR DESCRIPTION
**Pull request by caitong93**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR fixes** *(optional, close the issue(s) when PR gets merged)*:

Fixes https://github.com/caicloud/pangolin/issues/192

**Special notes for your reviewer**:

/cc @kdada @bbbmj 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by bbbmj** [comment]
@caitong93 测试了吗？

**Comment by caitong93** [comment]
@bbbmj 测过

**Pull request merged**
